import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import { ReactLenis } from './utils/lenis'
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const generalSans = localFont({
  src: [
    {
      path: "./fonts/GeneralSans-Medium.woff",
      weight: "400",
      style: "normal"
    },
    {
      path: "./fonts/GeneralSans-Regular.woff",
      weight: "300",
      style: "normal"
    },
  ],
  variable: "--font-general"

})
export const metadata = {
  title: "Artech 2000",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ReactLenis root>
        <body
          className={`${geistSans.variable} ${generalSans.variable} antialiased`}
        >

          {children}


        </body>
      </ReactLenis>
    </html>
  );
}
